#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RevMobBuddyExample.Android.Resource", IsApplication=true)]

namespace RevMobBuddyExample.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AdMobBuddy.Android.Resource.Attribute.adSize = global::RevMobBuddyExample.Android.Resource.Attribute.adSize;
			global::AdMobBuddy.Android.Resource.Attribute.adSizes = global::RevMobBuddyExample.Android.Resource.Attribute.adSizes;
			global::AdMobBuddy.Android.Resource.Attribute.adUnitId = global::RevMobBuddyExample.Android.Resource.Attribute.adUnitId;
			global::AdMobBuddy.Android.Resource.Attribute.alpha = global::RevMobBuddyExample.Android.Resource.Attribute.alpha;
			global::AdMobBuddy.Android.Resource.Attribute.coordinatorLayoutStyle = global::RevMobBuddyExample.Android.Resource.Attribute.coordinatorLayoutStyle;
			global::AdMobBuddy.Android.Resource.Attribute.font = global::RevMobBuddyExample.Android.Resource.Attribute.font;
			global::AdMobBuddy.Android.Resource.Attribute.fontProviderAuthority = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderAuthority;
			global::AdMobBuddy.Android.Resource.Attribute.fontProviderCerts = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderCerts;
			global::AdMobBuddy.Android.Resource.Attribute.fontProviderFetchStrategy = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderFetchStrategy;
			global::AdMobBuddy.Android.Resource.Attribute.fontProviderFetchTimeout = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderFetchTimeout;
			global::AdMobBuddy.Android.Resource.Attribute.fontProviderPackage = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderPackage;
			global::AdMobBuddy.Android.Resource.Attribute.fontProviderQuery = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderQuery;
			global::AdMobBuddy.Android.Resource.Attribute.fontStyle = global::RevMobBuddyExample.Android.Resource.Attribute.fontStyle;
			global::AdMobBuddy.Android.Resource.Attribute.fontVariationSettings = global::RevMobBuddyExample.Android.Resource.Attribute.fontVariationSettings;
			global::AdMobBuddy.Android.Resource.Attribute.fontWeight = global::RevMobBuddyExample.Android.Resource.Attribute.fontWeight;
			global::AdMobBuddy.Android.Resource.Attribute.keylines = global::RevMobBuddyExample.Android.Resource.Attribute.keylines;
			global::AdMobBuddy.Android.Resource.Attribute.layout_anchor = global::RevMobBuddyExample.Android.Resource.Attribute.layout_anchor;
			global::AdMobBuddy.Android.Resource.Attribute.layout_anchorGravity = global::RevMobBuddyExample.Android.Resource.Attribute.layout_anchorGravity;
			global::AdMobBuddy.Android.Resource.Attribute.layout_behavior = global::RevMobBuddyExample.Android.Resource.Attribute.layout_behavior;
			global::AdMobBuddy.Android.Resource.Attribute.layout_dodgeInsetEdges = global::RevMobBuddyExample.Android.Resource.Attribute.layout_dodgeInsetEdges;
			global::AdMobBuddy.Android.Resource.Attribute.layout_insetEdge = global::RevMobBuddyExample.Android.Resource.Attribute.layout_insetEdge;
			global::AdMobBuddy.Android.Resource.Attribute.layout_keyline = global::RevMobBuddyExample.Android.Resource.Attribute.layout_keyline;
			global::AdMobBuddy.Android.Resource.Attribute.statusBarBackground = global::RevMobBuddyExample.Android.Resource.Attribute.statusBarBackground;
			global::AdMobBuddy.Android.Resource.Attribute.ttcIndex = global::RevMobBuddyExample.Android.Resource.Attribute.ttcIndex;
			global::AdMobBuddy.Android.Resource.Color.notification_action_color_filter = global::RevMobBuddyExample.Android.Resource.Color.notification_action_color_filter;
			global::AdMobBuddy.Android.Resource.Color.notification_icon_bg_color = global::RevMobBuddyExample.Android.Resource.Color.notification_icon_bg_color;
			global::AdMobBuddy.Android.Resource.Color.notification_material_background_media_default_color = global::RevMobBuddyExample.Android.Resource.Color.notification_material_background_media_default_color;
			global::AdMobBuddy.Android.Resource.Color.primary_text_default_material_dark = global::RevMobBuddyExample.Android.Resource.Color.primary_text_default_material_dark;
			global::AdMobBuddy.Android.Resource.Color.secondary_text_default_material_dark = global::RevMobBuddyExample.Android.Resource.Color.secondary_text_default_material_dark;
			global::AdMobBuddy.Android.Resource.Dimension.compat_button_inset_horizontal_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_button_inset_horizontal_material;
			global::AdMobBuddy.Android.Resource.Dimension.compat_button_inset_vertical_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_button_inset_vertical_material;
			global::AdMobBuddy.Android.Resource.Dimension.compat_button_padding_horizontal_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_button_padding_horizontal_material;
			global::AdMobBuddy.Android.Resource.Dimension.compat_button_padding_vertical_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_button_padding_vertical_material;
			global::AdMobBuddy.Android.Resource.Dimension.compat_control_corner_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_control_corner_material;
			global::AdMobBuddy.Android.Resource.Dimension.compat_notification_large_icon_max_height = global::RevMobBuddyExample.Android.Resource.Dimension.compat_notification_large_icon_max_height;
			global::AdMobBuddy.Android.Resource.Dimension.compat_notification_large_icon_max_width = global::RevMobBuddyExample.Android.Resource.Dimension.compat_notification_large_icon_max_width;
			global::AdMobBuddy.Android.Resource.Dimension.notification_action_icon_size = global::RevMobBuddyExample.Android.Resource.Dimension.notification_action_icon_size;
			global::AdMobBuddy.Android.Resource.Dimension.notification_action_text_size = global::RevMobBuddyExample.Android.Resource.Dimension.notification_action_text_size;
			global::AdMobBuddy.Android.Resource.Dimension.notification_big_circle_margin = global::RevMobBuddyExample.Android.Resource.Dimension.notification_big_circle_margin;
			global::AdMobBuddy.Android.Resource.Dimension.notification_content_margin_start = global::RevMobBuddyExample.Android.Resource.Dimension.notification_content_margin_start;
			global::AdMobBuddy.Android.Resource.Dimension.notification_large_icon_height = global::RevMobBuddyExample.Android.Resource.Dimension.notification_large_icon_height;
			global::AdMobBuddy.Android.Resource.Dimension.notification_large_icon_width = global::RevMobBuddyExample.Android.Resource.Dimension.notification_large_icon_width;
			global::AdMobBuddy.Android.Resource.Dimension.notification_main_column_padding_top = global::RevMobBuddyExample.Android.Resource.Dimension.notification_main_column_padding_top;
			global::AdMobBuddy.Android.Resource.Dimension.notification_media_narrow_margin = global::RevMobBuddyExample.Android.Resource.Dimension.notification_media_narrow_margin;
			global::AdMobBuddy.Android.Resource.Dimension.notification_right_icon_size = global::RevMobBuddyExample.Android.Resource.Dimension.notification_right_icon_size;
			global::AdMobBuddy.Android.Resource.Dimension.notification_right_side_padding_top = global::RevMobBuddyExample.Android.Resource.Dimension.notification_right_side_padding_top;
			global::AdMobBuddy.Android.Resource.Dimension.notification_small_icon_background_padding = global::RevMobBuddyExample.Android.Resource.Dimension.notification_small_icon_background_padding;
			global::AdMobBuddy.Android.Resource.Dimension.notification_small_icon_size_as_large = global::RevMobBuddyExample.Android.Resource.Dimension.notification_small_icon_size_as_large;
			global::AdMobBuddy.Android.Resource.Dimension.notification_subtext_size = global::RevMobBuddyExample.Android.Resource.Dimension.notification_subtext_size;
			global::AdMobBuddy.Android.Resource.Dimension.notification_top_pad = global::RevMobBuddyExample.Android.Resource.Dimension.notification_top_pad;
			global::AdMobBuddy.Android.Resource.Dimension.notification_top_pad_large_text = global::RevMobBuddyExample.Android.Resource.Dimension.notification_top_pad_large_text;
			global::AdMobBuddy.Android.Resource.Drawable.notification_action_background = global::RevMobBuddyExample.Android.Resource.Drawable.notification_action_background;
			global::AdMobBuddy.Android.Resource.Drawable.notification_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg;
			global::AdMobBuddy.Android.Resource.Drawable.notification_bg_low = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_low;
			global::AdMobBuddy.Android.Resource.Drawable.notification_bg_low_normal = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_low_normal;
			global::AdMobBuddy.Android.Resource.Drawable.notification_bg_low_pressed = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_low_pressed;
			global::AdMobBuddy.Android.Resource.Drawable.notification_bg_normal = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_normal;
			global::AdMobBuddy.Android.Resource.Drawable.notification_bg_normal_pressed = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_normal_pressed;
			global::AdMobBuddy.Android.Resource.Drawable.notification_icon_background = global::RevMobBuddyExample.Android.Resource.Drawable.notification_icon_background;
			global::AdMobBuddy.Android.Resource.Drawable.notification_template_icon_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notification_template_icon_bg;
			global::AdMobBuddy.Android.Resource.Drawable.notification_template_icon_low_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notification_template_icon_low_bg;
			global::AdMobBuddy.Android.Resource.Drawable.notification_tile_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notification_tile_bg;
			global::AdMobBuddy.Android.Resource.Drawable.notify_panel_notification_icon_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notify_panel_notification_icon_bg;
			global::AdMobBuddy.Android.Resource.Id.action0 = global::RevMobBuddyExample.Android.Resource.Id.action0;
			global::AdMobBuddy.Android.Resource.Id.actions = global::RevMobBuddyExample.Android.Resource.Id.actions;
			global::AdMobBuddy.Android.Resource.Id.action_container = global::RevMobBuddyExample.Android.Resource.Id.action_container;
			global::AdMobBuddy.Android.Resource.Id.action_divider = global::RevMobBuddyExample.Android.Resource.Id.action_divider;
			global::AdMobBuddy.Android.Resource.Id.action_image = global::RevMobBuddyExample.Android.Resource.Id.action_image;
			global::AdMobBuddy.Android.Resource.Id.action_text = global::RevMobBuddyExample.Android.Resource.Id.action_text;
			global::AdMobBuddy.Android.Resource.Id.all = global::RevMobBuddyExample.Android.Resource.Id.all;
			global::AdMobBuddy.Android.Resource.Id.async = global::RevMobBuddyExample.Android.Resource.Id.async;
			global::AdMobBuddy.Android.Resource.Id.blocking = global::RevMobBuddyExample.Android.Resource.Id.blocking;
			global::AdMobBuddy.Android.Resource.Id.bottom = global::RevMobBuddyExample.Android.Resource.Id.bottom;
			global::AdMobBuddy.Android.Resource.Id.cancel_action = global::RevMobBuddyExample.Android.Resource.Id.cancel_action;
			global::AdMobBuddy.Android.Resource.Id.center = global::RevMobBuddyExample.Android.Resource.Id.center;
			global::AdMobBuddy.Android.Resource.Id.center_horizontal = global::RevMobBuddyExample.Android.Resource.Id.center_horizontal;
			global::AdMobBuddy.Android.Resource.Id.center_vertical = global::RevMobBuddyExample.Android.Resource.Id.center_vertical;
			global::AdMobBuddy.Android.Resource.Id.chronometer = global::RevMobBuddyExample.Android.Resource.Id.chronometer;
			global::AdMobBuddy.Android.Resource.Id.clip_horizontal = global::RevMobBuddyExample.Android.Resource.Id.clip_horizontal;
			global::AdMobBuddy.Android.Resource.Id.clip_vertical = global::RevMobBuddyExample.Android.Resource.Id.clip_vertical;
			global::AdMobBuddy.Android.Resource.Id.end = global::RevMobBuddyExample.Android.Resource.Id.end;
			global::AdMobBuddy.Android.Resource.Id.end_padder = global::RevMobBuddyExample.Android.Resource.Id.end_padder;
			global::AdMobBuddy.Android.Resource.Id.fill = global::RevMobBuddyExample.Android.Resource.Id.fill;
			global::AdMobBuddy.Android.Resource.Id.fill_horizontal = global::RevMobBuddyExample.Android.Resource.Id.fill_horizontal;
			global::AdMobBuddy.Android.Resource.Id.fill_vertical = global::RevMobBuddyExample.Android.Resource.Id.fill_vertical;
			global::AdMobBuddy.Android.Resource.Id.forever = global::RevMobBuddyExample.Android.Resource.Id.forever;
			global::AdMobBuddy.Android.Resource.Id.icon = global::RevMobBuddyExample.Android.Resource.Id.icon;
			global::AdMobBuddy.Android.Resource.Id.icon_group = global::RevMobBuddyExample.Android.Resource.Id.icon_group;
			global::AdMobBuddy.Android.Resource.Id.info = global::RevMobBuddyExample.Android.Resource.Id.info;
			global::AdMobBuddy.Android.Resource.Id.italic = global::RevMobBuddyExample.Android.Resource.Id.italic;
			global::AdMobBuddy.Android.Resource.Id.left = global::RevMobBuddyExample.Android.Resource.Id.left;
			global::AdMobBuddy.Android.Resource.Id.line1 = global::RevMobBuddyExample.Android.Resource.Id.line1;
			global::AdMobBuddy.Android.Resource.Id.line3 = global::RevMobBuddyExample.Android.Resource.Id.line3;
			global::AdMobBuddy.Android.Resource.Id.media_actions = global::RevMobBuddyExample.Android.Resource.Id.media_actions;
			global::AdMobBuddy.Android.Resource.Id.none = global::RevMobBuddyExample.Android.Resource.Id.none;
			global::AdMobBuddy.Android.Resource.Id.normal = global::RevMobBuddyExample.Android.Resource.Id.normal;
			global::AdMobBuddy.Android.Resource.Id.notification_background = global::RevMobBuddyExample.Android.Resource.Id.notification_background;
			global::AdMobBuddy.Android.Resource.Id.notification_main_column = global::RevMobBuddyExample.Android.Resource.Id.notification_main_column;
			global::AdMobBuddy.Android.Resource.Id.notification_main_column_container = global::RevMobBuddyExample.Android.Resource.Id.notification_main_column_container;
			global::AdMobBuddy.Android.Resource.Id.right = global::RevMobBuddyExample.Android.Resource.Id.right;
			global::AdMobBuddy.Android.Resource.Id.right_icon = global::RevMobBuddyExample.Android.Resource.Id.right_icon;
			global::AdMobBuddy.Android.Resource.Id.right_side = global::RevMobBuddyExample.Android.Resource.Id.right_side;
			global::AdMobBuddy.Android.Resource.Id.start = global::RevMobBuddyExample.Android.Resource.Id.start;
			global::AdMobBuddy.Android.Resource.Id.status_bar_latest_event_content = global::RevMobBuddyExample.Android.Resource.Id.status_bar_latest_event_content;
			global::AdMobBuddy.Android.Resource.Id.tag_transition_group = global::RevMobBuddyExample.Android.Resource.Id.tag_transition_group;
			global::AdMobBuddy.Android.Resource.Id.tag_unhandled_key_event_manager = global::RevMobBuddyExample.Android.Resource.Id.tag_unhandled_key_event_manager;
			global::AdMobBuddy.Android.Resource.Id.tag_unhandled_key_listeners = global::RevMobBuddyExample.Android.Resource.Id.tag_unhandled_key_listeners;
			global::AdMobBuddy.Android.Resource.Id.text = global::RevMobBuddyExample.Android.Resource.Id.text;
			global::AdMobBuddy.Android.Resource.Id.text2 = global::RevMobBuddyExample.Android.Resource.Id.text2;
			global::AdMobBuddy.Android.Resource.Id.time = global::RevMobBuddyExample.Android.Resource.Id.time;
			global::AdMobBuddy.Android.Resource.Id.title = global::RevMobBuddyExample.Android.Resource.Id.title;
			global::AdMobBuddy.Android.Resource.Id.top = global::RevMobBuddyExample.Android.Resource.Id.top;
			global::AdMobBuddy.Android.Resource.Integer.cancel_button_image_alpha = global::RevMobBuddyExample.Android.Resource.Integer.cancel_button_image_alpha;
			global::AdMobBuddy.Android.Resource.Integer.google_play_services_version = global::RevMobBuddyExample.Android.Resource.Integer.google_play_services_version;
			global::AdMobBuddy.Android.Resource.Integer.status_bar_notification_info_maxnum = global::RevMobBuddyExample.Android.Resource.Integer.status_bar_notification_info_maxnum;
			global::AdMobBuddy.Android.Resource.Layout.notification_action = global::RevMobBuddyExample.Android.Resource.Layout.notification_action;
			global::AdMobBuddy.Android.Resource.Layout.notification_action_tombstone = global::RevMobBuddyExample.Android.Resource.Layout.notification_action_tombstone;
			global::AdMobBuddy.Android.Resource.Layout.notification_media_action = global::RevMobBuddyExample.Android.Resource.Layout.notification_media_action;
			global::AdMobBuddy.Android.Resource.Layout.notification_media_cancel_action = global::RevMobBuddyExample.Android.Resource.Layout.notification_media_cancel_action;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_big_media = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_big_media;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_big_media_custom = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_big_media_custom;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_big_media_narrow = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_big_media_narrow;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_big_media_narrow_custom = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_big_media_narrow_custom;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_custom_big = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_custom_big;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_icon_group = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_icon_group;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_lines_media = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_lines_media;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_media = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_media;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_media_custom = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_media_custom;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_part_chronometer = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_part_chronometer;
			global::AdMobBuddy.Android.Resource.Layout.notification_template_part_time = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_part_time;
			global::AdMobBuddy.Android.Resource.String.app_name = global::RevMobBuddyExample.Android.Resource.String.app_name;
			global::AdMobBuddy.Android.Resource.String.common_google_play_services_unknown_issue = global::RevMobBuddyExample.Android.Resource.String.common_google_play_services_unknown_issue;
			global::AdMobBuddy.Android.Resource.String.hello = global::RevMobBuddyExample.Android.Resource.String.hello;
			global::AdMobBuddy.Android.Resource.String.status_bar_notification_info_overflow = global::RevMobBuddyExample.Android.Resource.String.status_bar_notification_info_overflow;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Info = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Info_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Info_Media;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Line2_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Line2_Media;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Media;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Time = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Time_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Time_Media;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Title = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::AdMobBuddy.Android.Resource.Style.TextAppearance_Compat_Notification_Title_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Title_Media;
			global::AdMobBuddy.Android.Resource.Style.Theme_IAPTheme = global::RevMobBuddyExample.Android.Resource.Style.Theme_IAPTheme;
			global::AdMobBuddy.Android.Resource.Style.Widget_Compat_NotificationActionContainer = global::RevMobBuddyExample.Android.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::AdMobBuddy.Android.Resource.Style.Widget_Compat_NotificationActionText = global::RevMobBuddyExample.Android.Resource.Style.Widget_Compat_NotificationActionText;
			global::AdMobBuddy.Android.Resource.Style.Widget_Support_CoordinatorLayout = global::RevMobBuddyExample.Android.Resource.Style.Widget_Support_CoordinatorLayout;
			global::AdMobBuddy.Android.Resource.Styleable.AdsAttrs = global::RevMobBuddyExample.Android.Resource.Styleable.AdsAttrs;
			global::AdMobBuddy.Android.Resource.Styleable.AdsAttrs_adSize = global::RevMobBuddyExample.Android.Resource.Styleable.AdsAttrs_adSize;
			global::AdMobBuddy.Android.Resource.Styleable.AdsAttrs_adSizes = global::RevMobBuddyExample.Android.Resource.Styleable.AdsAttrs_adSizes;
			global::AdMobBuddy.Android.Resource.Styleable.AdsAttrs_adUnitId = global::RevMobBuddyExample.Android.Resource.Styleable.AdsAttrs_adUnitId;
			global::AdMobBuddy.Android.Resource.Styleable.ColorStateListItem = global::RevMobBuddyExample.Android.Resource.Styleable.ColorStateListItem;
			global::AdMobBuddy.Android.Resource.Styleable.ColorStateListItem_alpha = global::RevMobBuddyExample.Android.Resource.Styleable.ColorStateListItem_alpha;
			global::AdMobBuddy.Android.Resource.Styleable.ColorStateListItem_android_alpha = global::RevMobBuddyExample.Android.Resource.Styleable.ColorStateListItem_android_alpha;
			global::AdMobBuddy.Android.Resource.Styleable.ColorStateListItem_android_color = global::RevMobBuddyExample.Android.Resource.Styleable.ColorStateListItem_android_color;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_keylines = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_keylines;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_Layout = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_Layout;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::AdMobBuddy.Android.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::RevMobBuddyExample.Android.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamily = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_android_font = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_android_font;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_android_fontStyle = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_android_fontWeight = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_font = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_font;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_fontStyle = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_fontStyle;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_fontWeight = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_fontWeight;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamilyFont_ttcIndex = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamily_fontProviderAuthority = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamily_fontProviderCerts = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderCerts;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamily_fontProviderPackage = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderPackage;
			global::AdMobBuddy.Android.Resource.Styleable.FontFamily_fontProviderQuery = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderQuery;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColorItem = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColorItem;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColorItem_android_color = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColorItem_android_color;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColorItem_android_offset = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColorItem_android_offset;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_centerColor = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_centerColor;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_centerX = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_centerX;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_centerY = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_centerY;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_endColor = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_endColor;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_endX = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_endX;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_endY = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_endY;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_gradientRadius = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_gradientRadius;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_startColor = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_startColor;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_startX = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_startX;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_startY = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_startY;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_tileMode = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_tileMode;
			global::AdMobBuddy.Android.Resource.Styleable.GradientColor_android_type = global::RevMobBuddyExample.Android.Resource.Styleable.GradientColor_android_type;
			global::FilenameBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::FilenameBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::FontBuddyLib.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::FontBuddyLib.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::GameTimer.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::GameTimer.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::HadoukInput.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::HadoukInput.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::InputHelper.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::InputHelper.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::MatrixExtensions.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::MatrixExtensions.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::MouseBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::MouseBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::PrimitiveBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::PrimitiveBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::RandomExtensions.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::RandomExtensions.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::ResolutionBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::ResolutionBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::StateMachineBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::StateMachineBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::TouchScreenBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::TouchScreenBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::Vector2Extensions.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::Vector2Extensions.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::XmlBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::XmlBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int fragment_fast_out_extra_slow_in = 2130771968;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int fragment_close_enter = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int fragment_close_exit = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fragment_fade_enter = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fragment_fade_exit = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fragment_open_enter = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fragment_open_exit = 2130837509;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int adSize = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int adSizes = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int adUnitId = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int alpha = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int coordinatorLayoutStyle = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int drawerLayoutStyle = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int elevation = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int font = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int fontProviderAuthority = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int fontProviderCerts = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int fontProviderFetchStrategy = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int fontProviderFetchTimeout = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int fontProviderPackage = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int fontProviderQuery = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int fontStyle = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int fontVariationSettings = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int fontWeight = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int keylines = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int layout_anchor = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int layout_anchorGravity = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int layout_behavior = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int layout_dodgeInsetEdges = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int layout_insetEdge = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int layout_keyline = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int statusBarBackground = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int swipeRefreshLayoutProgressSpinnerBackgroundColor = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int ttcIndex = 2130903066;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F040000
			public const int enable_system_alarm_service_default = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int enable_system_foreground_service_default = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int enable_system_job_service_default = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int workmanager_test_configuration = 2130968579;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F050000
			public const int androidx_core_ripple_material_light = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int androidx_core_secondary_text_default_material_light = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int notification_action_color_filter = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int notification_icon_bg_color = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int notification_material_background_media_default_color = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int primary_text_default_material_dark = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int secondary_text_default_material_dark = 2131034118;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F060000
			public const int compat_button_inset_horizontal_material = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int compat_button_inset_vertical_material = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int compat_button_padding_horizontal_material = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int compat_button_padding_vertical_material = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int compat_control_corner_material = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int compat_notification_large_icon_max_height = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int compat_notification_large_icon_max_width = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int def_drawer_elevation = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int notification_action_icon_size = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int notification_action_text_size = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int notification_big_circle_margin = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int notification_content_margin_start = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int notification_large_icon_height = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int notification_large_icon_width = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int notification_main_column_padding_top = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int notification_media_narrow_margin = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int notification_right_icon_size = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int notification_right_side_padding_top = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int notification_small_icon_background_padding = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int notification_small_icon_size_as_large = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int notification_subtext_size = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int notification_top_pad = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int notification_top_pad_large_text = 2131099670;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F070000
			public const int Icon = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int notification_action_background = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int notification_bg = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int notification_bg_low = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int notification_bg_low_normal = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_bg_low_pressed = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_bg_normal = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_bg_normal_pressed = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int notification_icon_background = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int notification_template_icon_bg = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int notification_template_icon_low_bg = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int notification_tile_bg = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int notify_panel_notification_icon_bg = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int Splash = 2131165197;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F080000
			public const int accessibility_action_clickable_span = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int accessibility_custom_action_0 = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int accessibility_custom_action_1 = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int accessibility_custom_action_10 = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int accessibility_custom_action_11 = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int accessibility_custom_action_12 = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int accessibility_custom_action_13 = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int accessibility_custom_action_14 = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int accessibility_custom_action_15 = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int accessibility_custom_action_16 = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int accessibility_custom_action_17 = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int accessibility_custom_action_18 = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int accessibility_custom_action_19 = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int accessibility_custom_action_2 = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int accessibility_custom_action_20 = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int accessibility_custom_action_21 = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int accessibility_custom_action_22 = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int accessibility_custom_action_23 = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int accessibility_custom_action_24 = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int accessibility_custom_action_25 = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int accessibility_custom_action_26 = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int accessibility_custom_action_27 = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int accessibility_custom_action_28 = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int accessibility_custom_action_29 = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int accessibility_custom_action_3 = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int accessibility_custom_action_30 = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int accessibility_custom_action_31 = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int accessibility_custom_action_4 = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public const int accessibility_custom_action_5 = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public const int accessibility_custom_action_6 = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public const int accessibility_custom_action_7 = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public const int accessibility_custom_action_8 = 2131230751;
			
			// aapt resource value: 0x7F080020
			public const int accessibility_custom_action_9 = 2131230752;
			
			// aapt resource value: 0x7F080021
			public const int action0 = 2131230753;
			
			// aapt resource value: 0x7F080026
			public const int actions = 2131230758;
			
			// aapt resource value: 0x7F080022
			public const int action_container = 2131230754;
			
			// aapt resource value: 0x7F080023
			public const int action_divider = 2131230755;
			
			// aapt resource value: 0x7F080024
			public const int action_image = 2131230756;
			
			// aapt resource value: 0x7F080025
			public const int action_text = 2131230757;
			
			// aapt resource value: 0x7F080027
			public const int all = 2131230759;
			
			// aapt resource value: 0x7F080028
			public const int async = 2131230760;
			
			// aapt resource value: 0x7F080029
			public const int blocking = 2131230761;
			
			// aapt resource value: 0x7F08002A
			public const int bottom = 2131230762;
			
			// aapt resource value: 0x7F08002B
			public const int cancel_action = 2131230763;
			
			// aapt resource value: 0x7F08002C
			public const int center = 2131230764;
			
			// aapt resource value: 0x7F08002D
			public const int center_horizontal = 2131230765;
			
			// aapt resource value: 0x7F08002E
			public const int center_vertical = 2131230766;
			
			// aapt resource value: 0x7F08002F
			public const int chronometer = 2131230767;
			
			// aapt resource value: 0x7F080030
			public const int clip_horizontal = 2131230768;
			
			// aapt resource value: 0x7F080031
			public const int clip_vertical = 2131230769;
			
			// aapt resource value: 0x7F080032
			public const int dialog_button = 2131230770;
			
			// aapt resource value: 0x7F080033
			public const int end = 2131230771;
			
			// aapt resource value: 0x7F080034
			public const int end_padder = 2131230772;
			
			// aapt resource value: 0x7F080035
			public const int fill = 2131230773;
			
			// aapt resource value: 0x7F080036
			public const int fill_horizontal = 2131230774;
			
			// aapt resource value: 0x7F080037
			public const int fill_vertical = 2131230775;
			
			// aapt resource value: 0x7F080038
			public const int forever = 2131230776;
			
			// aapt resource value: 0x7F080039
			public const int fragment_container_view_tag = 2131230777;
			
			// aapt resource value: 0x7F08003A
			public const int icon = 2131230778;
			
			// aapt resource value: 0x7F08003B
			public const int icon_group = 2131230779;
			
			// aapt resource value: 0x7F08003C
			public const int info = 2131230780;
			
			// aapt resource value: 0x7F08003D
			public const int italic = 2131230781;
			
			// aapt resource value: 0x7F08003E
			public const int left = 2131230782;
			
			// aapt resource value: 0x7F08003F
			public const int line1 = 2131230783;
			
			// aapt resource value: 0x7F080040
			public const int line3 = 2131230784;
			
			// aapt resource value: 0x7F080041
			public const int media_actions = 2131230785;
			
			// aapt resource value: 0x7F080042
			public const int media_controller_compat_view_tag = 2131230786;
			
			// aapt resource value: 0x7F080043
			public const int none = 2131230787;
			
			// aapt resource value: 0x7F080044
			public const int normal = 2131230788;
			
			// aapt resource value: 0x7F080045
			public const int notification_background = 2131230789;
			
			// aapt resource value: 0x7F080046
			public const int notification_main_column = 2131230790;
			
			// aapt resource value: 0x7F080047
			public const int notification_main_column_container = 2131230791;
			
			// aapt resource value: 0x7F080048
			public const int right = 2131230792;
			
			// aapt resource value: 0x7F080049
			public const int right_icon = 2131230793;
			
			// aapt resource value: 0x7F08004A
			public const int right_side = 2131230794;
			
			// aapt resource value: 0x7F08004B
			public const int special_effects_controller_view_tag = 2131230795;
			
			// aapt resource value: 0x7F08004C
			public const int start = 2131230796;
			
			// aapt resource value: 0x7F08004D
			public const int status_bar_latest_event_content = 2131230797;
			
			// aapt resource value: 0x7F08004E
			public const int tag_accessibility_actions = 2131230798;
			
			// aapt resource value: 0x7F08004F
			public const int tag_accessibility_clickable_spans = 2131230799;
			
			// aapt resource value: 0x7F080050
			public const int tag_accessibility_heading = 2131230800;
			
			// aapt resource value: 0x7F080051
			public const int tag_accessibility_pane_title = 2131230801;
			
			// aapt resource value: 0x7F080052
			public const int tag_screen_reader_focusable = 2131230802;
			
			// aapt resource value: 0x7F080053
			public const int tag_transition_group = 2131230803;
			
			// aapt resource value: 0x7F080054
			public const int tag_unhandled_key_event_manager = 2131230804;
			
			// aapt resource value: 0x7F080055
			public const int tag_unhandled_key_listeners = 2131230805;
			
			// aapt resource value: 0x7F080056
			public const int text = 2131230806;
			
			// aapt resource value: 0x7F080057
			public const int text2 = 2131230807;
			
			// aapt resource value: 0x7F080058
			public const int time = 2131230808;
			
			// aapt resource value: 0x7F080059
			public const int title = 2131230809;
			
			// aapt resource value: 0x7F08005A
			public const int top = 2131230810;
			
			// aapt resource value: 0x7F08005B
			public const int view_tree_lifecycle_owner = 2131230811;
			
			// aapt resource value: 0x7F08005C
			public const int view_tree_saved_state_registry_owner = 2131230812;
			
			// aapt resource value: 0x7F08005D
			public const int view_tree_view_model_store_owner = 2131230813;
			
			// aapt resource value: 0x7F08005E
			public const int visible_removing_fragment_view_tag = 2131230814;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int cancel_button_image_alpha = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int google_play_services_version = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int status_bar_notification_info_maxnum = 2131296258;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F0A0000
			public const int custom_dialog = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int notification_action = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int notification_action_tombstone = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int notification_media_action = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int notification_media_cancel_action = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int notification_template_big_media = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int notification_template_big_media_custom = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int notification_template_big_media_narrow = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int notification_template_big_media_narrow_custom = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int notification_template_custom_big = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int notification_template_icon_group = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int notification_template_lines_media = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public const int notification_template_media = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public const int notification_template_media_custom = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int notification_template_part_chronometer = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int notification_template_part_time = 2131361807;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0000
			public const int ApplicationName = 2131427328;
			
			// aapt resource value: 0x7F0B0002
			public const int app_name = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int common_google_play_services_unknown_issue = 2131427331;
			
			// aapt resource value: 0x7F0B0001
			public const int Hello = 2131427329;
			
			// aapt resource value: 0x7F0B0004
			public const int hello = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int status_bar_notification_info_overflow = 2131427333;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int TextAppearance_Compat_Notification = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int TextAppearance_Compat_Notification_Info = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int TextAppearance_Compat_Notification_Info_Media = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int TextAppearance_Compat_Notification_Line2 = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int TextAppearance_Compat_Notification_Media = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int TextAppearance_Compat_Notification_Time = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int TextAppearance_Compat_Notification_Time_Media = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public const int TextAppearance_Compat_Notification_Title = 2131492872;
			
			// aapt resource value: 0x7F0C0009
			public const int TextAppearance_Compat_Notification_Title_Media = 2131492873;
			
			// aapt resource value: 0x7F0C000A
			public const int Theme_IAPTheme = 2131492874;
			
			// aapt resource value: 0x7F0C000B
			public const int Theme_Splash = 2131492875;
			
			// aapt resource value: 0x7F0C000C
			public const int Widget_Compat_NotificationActionContainer = 2131492876;
			
			// aapt resource value: 0x7F0C000D
			public const int Widget_Compat_NotificationActionText = 2131492877;
			
			// aapt resource value: 0x7F0C000E
			public const int Widget_Support_CoordinatorLayout = 2131492878;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F030000,0x7F030001,0x7F030002 }
			public static int[] AdsAttrs = new int[] {
					2130903040,
					2130903041,
					2130903042};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F030003 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130903043};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F030011,0x7F030018 }
			public static int[] CoordinatorLayout = new int[] {
					2130903057,
					2130903064};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F030012,0x7F030013,0x7F030014,0x7F030015,0x7F030016,0x7F030017 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130903058,
					2130903059,
					2130903060,
					2130903061,
					2130903062,
					2130903063};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F030006 }
			public static int[] DrawerLayout = new int[] {
					2130903046};
			
			// aapt resource value: 0
			public const int DrawerLayout_elevation = 0;
			
			// aapt resource value: { 0x7F030008,0x7F030009,0x7F03000A,0x7F03000B,0x7F03000C,0x7F03000D }
			public static int[] FontFamily = new int[] {
					2130903048,
					2130903049,
					2130903050,
					2130903051,
					2130903052,
					2130903053};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F030007,0x7F03000E,0x7F03000F,0x7F030010,0x7F03001A }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130903047,
					2130903054,
					2130903055,
					2130903056,
					2130903066};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x1010003,0x10100D0,0x10100D1 }
			public static int[] Fragment = new int[] {
					16842755,
					16842960,
					16842961};
			
			// aapt resource value: { 0x1010003,0x10100D1 }
			public static int[] FragmentContainerView = new int[] {
					16842755,
					16842961};
			
			// aapt resource value: 0
			public const int FragmentContainerView_android_name = 0;
			
			// aapt resource value: 1
			public const int FragmentContainerView_android_tag = 1;
			
			// aapt resource value: 1
			public const int Fragment_android_id = 1;
			
			// aapt resource value: 0
			public const int Fragment_android_name = 0;
			
			// aapt resource value: 2
			public const int Fragment_android_tag = 2;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F030019 }
			public static int[] SwipeRefreshLayout = new int[] {
					2130903065};
			
			// aapt resource value: 0
			public const int SwipeRefreshLayout_swipeRefreshLayoutProgressSpinnerBackgroundColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
