#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RevMobBuddyExample.Android.Resource", IsApplication=true)]

namespace RevMobBuddyExample.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AdMobMonoGame.Android.Resource.Attribute.adSize = global::RevMobBuddyExample.Android.Resource.Attribute.adSize;
			global::AdMobMonoGame.Android.Resource.Attribute.adSizes = global::RevMobBuddyExample.Android.Resource.Attribute.adSizes;
			global::AdMobMonoGame.Android.Resource.Attribute.adUnitId = global::RevMobBuddyExample.Android.Resource.Attribute.adUnitId;
			global::AdMobMonoGame.Android.Resource.Attribute.font = global::RevMobBuddyExample.Android.Resource.Attribute.font;
			global::AdMobMonoGame.Android.Resource.Attribute.fontProviderAuthority = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderAuthority;
			global::AdMobMonoGame.Android.Resource.Attribute.fontProviderCerts = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderCerts;
			global::AdMobMonoGame.Android.Resource.Attribute.fontProviderFetchStrategy = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderFetchStrategy;
			global::AdMobMonoGame.Android.Resource.Attribute.fontProviderFetchTimeout = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderFetchTimeout;
			global::AdMobMonoGame.Android.Resource.Attribute.fontProviderPackage = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderPackage;
			global::AdMobMonoGame.Android.Resource.Attribute.fontProviderQuery = global::RevMobBuddyExample.Android.Resource.Attribute.fontProviderQuery;
			global::AdMobMonoGame.Android.Resource.Attribute.fontStyle = global::RevMobBuddyExample.Android.Resource.Attribute.fontStyle;
			global::AdMobMonoGame.Android.Resource.Attribute.fontWeight = global::RevMobBuddyExample.Android.Resource.Attribute.fontWeight;
			global::AdMobMonoGame.Android.Resource.Boolean.abc_action_bar_embed_tabs = global::RevMobBuddyExample.Android.Resource.Boolean.abc_action_bar_embed_tabs;
			global::AdMobMonoGame.Android.Resource.Color.notification_action_color_filter = global::RevMobBuddyExample.Android.Resource.Color.notification_action_color_filter;
			global::AdMobMonoGame.Android.Resource.Color.notification_icon_bg_color = global::RevMobBuddyExample.Android.Resource.Color.notification_icon_bg_color;
			global::AdMobMonoGame.Android.Resource.Color.notification_material_background_media_default_color = global::RevMobBuddyExample.Android.Resource.Color.notification_material_background_media_default_color;
			global::AdMobMonoGame.Android.Resource.Color.primary_text_default_material_dark = global::RevMobBuddyExample.Android.Resource.Color.primary_text_default_material_dark;
			global::AdMobMonoGame.Android.Resource.Color.ripple_material_light = global::RevMobBuddyExample.Android.Resource.Color.ripple_material_light;
			global::AdMobMonoGame.Android.Resource.Color.secondary_text_default_material_dark = global::RevMobBuddyExample.Android.Resource.Color.secondary_text_default_material_dark;
			global::AdMobMonoGame.Android.Resource.Color.secondary_text_default_material_light = global::RevMobBuddyExample.Android.Resource.Color.secondary_text_default_material_light;
			global::AdMobMonoGame.Android.Resource.Dimension.compat_button_inset_horizontal_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_button_inset_horizontal_material;
			global::AdMobMonoGame.Android.Resource.Dimension.compat_button_inset_vertical_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_button_inset_vertical_material;
			global::AdMobMonoGame.Android.Resource.Dimension.compat_button_padding_horizontal_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_button_padding_horizontal_material;
			global::AdMobMonoGame.Android.Resource.Dimension.compat_button_padding_vertical_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_button_padding_vertical_material;
			global::AdMobMonoGame.Android.Resource.Dimension.compat_control_corner_material = global::RevMobBuddyExample.Android.Resource.Dimension.compat_control_corner_material;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_action_icon_size = global::RevMobBuddyExample.Android.Resource.Dimension.notification_action_icon_size;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_action_text_size = global::RevMobBuddyExample.Android.Resource.Dimension.notification_action_text_size;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_big_circle_margin = global::RevMobBuddyExample.Android.Resource.Dimension.notification_big_circle_margin;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_content_margin_start = global::RevMobBuddyExample.Android.Resource.Dimension.notification_content_margin_start;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_large_icon_height = global::RevMobBuddyExample.Android.Resource.Dimension.notification_large_icon_height;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_large_icon_width = global::RevMobBuddyExample.Android.Resource.Dimension.notification_large_icon_width;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_main_column_padding_top = global::RevMobBuddyExample.Android.Resource.Dimension.notification_main_column_padding_top;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_media_narrow_margin = global::RevMobBuddyExample.Android.Resource.Dimension.notification_media_narrow_margin;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_right_icon_size = global::RevMobBuddyExample.Android.Resource.Dimension.notification_right_icon_size;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_right_side_padding_top = global::RevMobBuddyExample.Android.Resource.Dimension.notification_right_side_padding_top;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_small_icon_background_padding = global::RevMobBuddyExample.Android.Resource.Dimension.notification_small_icon_background_padding;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_small_icon_size_as_large = global::RevMobBuddyExample.Android.Resource.Dimension.notification_small_icon_size_as_large;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_subtext_size = global::RevMobBuddyExample.Android.Resource.Dimension.notification_subtext_size;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_top_pad = global::RevMobBuddyExample.Android.Resource.Dimension.notification_top_pad;
			global::AdMobMonoGame.Android.Resource.Dimension.notification_top_pad_large_text = global::RevMobBuddyExample.Android.Resource.Dimension.notification_top_pad_large_text;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_action_background = global::RevMobBuddyExample.Android.Resource.Drawable.notification_action_background;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_bg_low = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_low;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_bg_low_normal = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_low_normal;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_bg_low_pressed = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_low_pressed;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_bg_normal = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_normal;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_bg_normal_pressed = global::RevMobBuddyExample.Android.Resource.Drawable.notification_bg_normal_pressed;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_icon_background = global::RevMobBuddyExample.Android.Resource.Drawable.notification_icon_background;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_template_icon_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notification_template_icon_bg;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_template_icon_low_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notification_template_icon_low_bg;
			global::AdMobMonoGame.Android.Resource.Drawable.notification_tile_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notification_tile_bg;
			global::AdMobMonoGame.Android.Resource.Drawable.notify_panel_notification_icon_bg = global::RevMobBuddyExample.Android.Resource.Drawable.notify_panel_notification_icon_bg;
			global::AdMobMonoGame.Android.Resource.Id.action0 = global::RevMobBuddyExample.Android.Resource.Id.action0;
			global::AdMobMonoGame.Android.Resource.Id.action_container = global::RevMobBuddyExample.Android.Resource.Id.action_container;
			global::AdMobMonoGame.Android.Resource.Id.action_divider = global::RevMobBuddyExample.Android.Resource.Id.action_divider;
			global::AdMobMonoGame.Android.Resource.Id.action_image = global::RevMobBuddyExample.Android.Resource.Id.action_image;
			global::AdMobMonoGame.Android.Resource.Id.action_text = global::RevMobBuddyExample.Android.Resource.Id.action_text;
			global::AdMobMonoGame.Android.Resource.Id.actions = global::RevMobBuddyExample.Android.Resource.Id.actions;
			global::AdMobMonoGame.Android.Resource.Id.async = global::RevMobBuddyExample.Android.Resource.Id.async;
			global::AdMobMonoGame.Android.Resource.Id.blocking = global::RevMobBuddyExample.Android.Resource.Id.blocking;
			global::AdMobMonoGame.Android.Resource.Id.cancel_action = global::RevMobBuddyExample.Android.Resource.Id.cancel_action;
			global::AdMobMonoGame.Android.Resource.Id.chronometer = global::RevMobBuddyExample.Android.Resource.Id.chronometer;
			global::AdMobMonoGame.Android.Resource.Id.end_padder = global::RevMobBuddyExample.Android.Resource.Id.end_padder;
			global::AdMobMonoGame.Android.Resource.Id.forever = global::RevMobBuddyExample.Android.Resource.Id.forever;
			global::AdMobMonoGame.Android.Resource.Id.icon = global::RevMobBuddyExample.Android.Resource.Id.icon;
			global::AdMobMonoGame.Android.Resource.Id.icon_group = global::RevMobBuddyExample.Android.Resource.Id.icon_group;
			global::AdMobMonoGame.Android.Resource.Id.info = global::RevMobBuddyExample.Android.Resource.Id.info;
			global::AdMobMonoGame.Android.Resource.Id.italic = global::RevMobBuddyExample.Android.Resource.Id.italic;
			global::AdMobMonoGame.Android.Resource.Id.line1 = global::RevMobBuddyExample.Android.Resource.Id.line1;
			global::AdMobMonoGame.Android.Resource.Id.line3 = global::RevMobBuddyExample.Android.Resource.Id.line3;
			global::AdMobMonoGame.Android.Resource.Id.media_actions = global::RevMobBuddyExample.Android.Resource.Id.media_actions;
			global::AdMobMonoGame.Android.Resource.Id.normal = global::RevMobBuddyExample.Android.Resource.Id.normal;
			global::AdMobMonoGame.Android.Resource.Id.notification_background = global::RevMobBuddyExample.Android.Resource.Id.notification_background;
			global::AdMobMonoGame.Android.Resource.Id.notification_main_column = global::RevMobBuddyExample.Android.Resource.Id.notification_main_column;
			global::AdMobMonoGame.Android.Resource.Id.notification_main_column_container = global::RevMobBuddyExample.Android.Resource.Id.notification_main_column_container;
			global::AdMobMonoGame.Android.Resource.Id.right_icon = global::RevMobBuddyExample.Android.Resource.Id.right_icon;
			global::AdMobMonoGame.Android.Resource.Id.right_side = global::RevMobBuddyExample.Android.Resource.Id.right_side;
			global::AdMobMonoGame.Android.Resource.Id.status_bar_latest_event_content = global::RevMobBuddyExample.Android.Resource.Id.status_bar_latest_event_content;
			global::AdMobMonoGame.Android.Resource.Id.tag_transition_group = global::RevMobBuddyExample.Android.Resource.Id.tag_transition_group;
			global::AdMobMonoGame.Android.Resource.Id.text = global::RevMobBuddyExample.Android.Resource.Id.text;
			global::AdMobMonoGame.Android.Resource.Id.text2 = global::RevMobBuddyExample.Android.Resource.Id.text2;
			global::AdMobMonoGame.Android.Resource.Id.time = global::RevMobBuddyExample.Android.Resource.Id.time;
			global::AdMobMonoGame.Android.Resource.Id.title = global::RevMobBuddyExample.Android.Resource.Id.title;
			global::AdMobMonoGame.Android.Resource.Integer.cancel_button_image_alpha = global::RevMobBuddyExample.Android.Resource.Integer.cancel_button_image_alpha;
			global::AdMobMonoGame.Android.Resource.Integer.google_play_services_version = global::RevMobBuddyExample.Android.Resource.Integer.google_play_services_version;
			global::AdMobMonoGame.Android.Resource.Integer.status_bar_notification_info_maxnum = global::RevMobBuddyExample.Android.Resource.Integer.status_bar_notification_info_maxnum;
			global::AdMobMonoGame.Android.Resource.Layout.notification_action = global::RevMobBuddyExample.Android.Resource.Layout.notification_action;
			global::AdMobMonoGame.Android.Resource.Layout.notification_action_tombstone = global::RevMobBuddyExample.Android.Resource.Layout.notification_action_tombstone;
			global::AdMobMonoGame.Android.Resource.Layout.notification_media_action = global::RevMobBuddyExample.Android.Resource.Layout.notification_media_action;
			global::AdMobMonoGame.Android.Resource.Layout.notification_media_cancel_action = global::RevMobBuddyExample.Android.Resource.Layout.notification_media_cancel_action;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_big_media = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_big_media;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_big_media_custom = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_big_media_custom;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_big_media_narrow = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_big_media_narrow;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_big_media_narrow_custom = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_big_media_narrow_custom;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_custom_big = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_custom_big;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_icon_group = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_icon_group;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_lines_media = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_lines_media;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_media = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_media;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_media_custom = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_media_custom;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_part_chronometer = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_part_chronometer;
			global::AdMobMonoGame.Android.Resource.Layout.notification_template_part_time = global::RevMobBuddyExample.Android.Resource.Layout.notification_template_part_time;
			global::AdMobMonoGame.Android.Resource.String.app_name = global::RevMobBuddyExample.Android.Resource.String.app_name;
			global::AdMobMonoGame.Android.Resource.String.common_google_play_services_unknown_issue = global::RevMobBuddyExample.Android.Resource.String.common_google_play_services_unknown_issue;
			global::AdMobMonoGame.Android.Resource.String.hello = global::RevMobBuddyExample.Android.Resource.String.hello;
			global::AdMobMonoGame.Android.Resource.String.status_bar_notification_info_overflow = global::RevMobBuddyExample.Android.Resource.String.status_bar_notification_info_overflow;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Info = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Info_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Info_Media;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Line2_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Line2_Media;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Media;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Time = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Time_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Time_Media;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Title = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::AdMobMonoGame.Android.Resource.Style.TextAppearance_Compat_Notification_Title_Media = global::RevMobBuddyExample.Android.Resource.Style.TextAppearance_Compat_Notification_Title_Media;
			global::AdMobMonoGame.Android.Resource.Style.Theme_IAPTheme = global::RevMobBuddyExample.Android.Resource.Style.Theme_IAPTheme;
			global::AdMobMonoGame.Android.Resource.Style.Widget_Compat_NotificationActionContainer = global::RevMobBuddyExample.Android.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::AdMobMonoGame.Android.Resource.Style.Widget_Compat_NotificationActionText = global::RevMobBuddyExample.Android.Resource.Style.Widget_Compat_NotificationActionText;
			global::AdMobMonoGame.Android.Resource.Styleable.AdsAttrs = global::RevMobBuddyExample.Android.Resource.Styleable.AdsAttrs;
			global::AdMobMonoGame.Android.Resource.Styleable.AdsAttrs_adSize = global::RevMobBuddyExample.Android.Resource.Styleable.AdsAttrs_adSize;
			global::AdMobMonoGame.Android.Resource.Styleable.AdsAttrs_adSizes = global::RevMobBuddyExample.Android.Resource.Styleable.AdsAttrs_adSizes;
			global::AdMobMonoGame.Android.Resource.Styleable.AdsAttrs_adUnitId = global::RevMobBuddyExample.Android.Resource.Styleable.AdsAttrs_adUnitId;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamily = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamily_fontProviderAuthority = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamily_fontProviderCerts = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderCerts;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamily_fontProviderPackage = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderPackage;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamily_fontProviderQuery = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamily_fontProviderQuery;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamilyFont = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamilyFont_android_font = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_android_font;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamilyFont_android_fontStyle = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamilyFont_android_fontWeight = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamilyFont_font = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_font;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamilyFont_fontStyle = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_fontStyle;
			global::AdMobMonoGame.Android.Resource.Styleable.FontFamilyFont_fontWeight = global::RevMobBuddyExample.Android.Resource.Styleable.FontFamilyFont_fontWeight;
			global::FilenameBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::FilenameBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::FontBuddyLib.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::FontBuddyLib.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::GameTimer.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::GameTimer.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::HadoukInput.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::HadoukInput.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::InputHelper.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::InputHelper.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::MatrixExtensions.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::MatrixExtensions.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::MouseBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::MouseBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::PrimitiveBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::PrimitiveBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::RandomExtensions.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::RandomExtensions.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::ResolutionBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::ResolutionBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::StateMachineBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::StateMachineBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::TouchScreenBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::TouchScreenBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::Vector2Extensions.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::Vector2Extensions.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
			global::XmlBuddy.Android.Resource.String.ApplicationName = global::RevMobBuddyExample.Android.Resource.String.ApplicationName;
			global::XmlBuddy.Android.Resource.String.Hello = global::RevMobBuddyExample.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int font = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderAuthority = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderCerts = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int fontProviderFetchStrategy = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fontProviderFetchTimeout = 2130771976;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderPackage = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderQuery = 2130771973;
			
			// aapt resource value: 0x7f010009
			public const int fontStyle = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int fontWeight = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int notification_action_color_filter = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int notification_icon_bg_color = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int notification_material_background_media_default_color = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int primary_text_default_material_dark = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int ripple_material_light = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int secondary_text_default_material_dark = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int secondary_text_default_material_light = 2131165190;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public const int compat_button_inset_horizontal_material = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int compat_button_inset_vertical_material = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int compat_button_padding_horizontal_material = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int compat_button_padding_vertical_material = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int compat_control_corner_material = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int notification_action_icon_size = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int notification_action_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int notification_big_circle_margin = 2131296267;
			
			// aapt resource value: 0x7f090001
			public const int notification_content_margin_start = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int notification_large_icon_height = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int notification_large_icon_width = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int notification_main_column_padding_top = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int notification_media_narrow_margin = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int notification_right_icon_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int notification_right_side_padding_top = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public const int notification_small_icon_background_padding = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int notification_small_icon_size_as_large = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int notification_subtext_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int notification_top_pad = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int notification_top_pad_large_text = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_template_icon_low_bg = 2130837517;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Splash = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000e
			public const int action0 = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public const int action_container = 2131361803;
			
			// aapt resource value: 0x7f0a0012
			public const int action_divider = 2131361810;
			
			// aapt resource value: 0x7f0a000c
			public const int action_image = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int action_text = 2131361805;
			
			// aapt resource value: 0x7f0a001c
			public const int actions = 2131361820;
			
			// aapt resource value: 0x7f0a0006
			public const int async = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int blocking = 2131361799;
			
			// aapt resource value: 0x7f0a000f
			public const int cancel_action = 2131361807;
			
			// aapt resource value: 0x7f0a0017
			public const int chronometer = 2131361815;
			
			// aapt resource value: 0x7f0a001e
			public const int end_padder = 2131361822;
			
			// aapt resource value: 0x7f0a0008
			public const int forever = 2131361800;
			
			// aapt resource value: 0x7f0a0019
			public const int icon = 2131361817;
			
			// aapt resource value: 0x7f0a001d
			public const int icon_group = 2131361821;
			
			// aapt resource value: 0x7f0a0018
			public const int info = 2131361816;
			
			// aapt resource value: 0x7f0a0009
			public const int italic = 2131361801;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0011
			public const int media_actions = 2131361809;
			
			// aapt resource value: 0x7f0a000a
			public const int normal = 2131361802;
			
			// aapt resource value: 0x7f0a001b
			public const int notification_background = 2131361819;
			
			// aapt resource value: 0x7f0a0014
			public const int notification_main_column = 2131361812;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_main_column_container = 2131361811;
			
			// aapt resource value: 0x7f0a001a
			public const int right_icon = 2131361818;
			
			// aapt resource value: 0x7f0a0015
			public const int right_side = 2131361813;
			
			// aapt resource value: 0x7f0a0010
			public const int status_bar_latest_event_content = 2131361808;
			
			// aapt resource value: 0x7f0a0002
			public const int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int text2 = 2131361796;
			
			// aapt resource value: 0x7f0a0016
			public const int time = 2131361814;
			
			// aapt resource value: 0x7f0a0005
			public const int title = 2131361797;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int cancel_button_image_alpha = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int status_bar_notification_info_maxnum = 2131034114;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int notification_action = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action_tombstone = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_media_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_media_cancel_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_big_media = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_big_media_custom = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media_narrow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_narrow_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_custom_big = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_icon_group = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_lines_media = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_media_custom = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_part_chronometer = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_part_time = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int hello = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int status_bar_notification_info_overflow = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060006
			public const int TextAppearance_Compat_Notification = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int TextAppearance_Compat_Notification_Info = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int TextAppearance_Compat_Notification_Info_Media = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int TextAppearance_Compat_Notification_Line2 = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int TextAppearance_Compat_Notification_Media = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int TextAppearance_Compat_Notification_Time = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int TextAppearance_Compat_Notification_Time_Media = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int TextAppearance_Compat_Notification_Title = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int TextAppearance_Compat_Notification_Title_Media = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int Theme_IAPTheme = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int Theme_Splash = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int Widget_Compat_NotificationActionContainer = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int Widget_Compat_NotificationActionText = 2131099659;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] FontFamily = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
