#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("sampleApp.Droid.Resource", IsApplication=true)]

namespace sampleApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050017
			public const int banner = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int bannerCustomSize = 2131034134;
			
			// aapt resource value: 0x7f050000
			public const int buttons = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int hideBanner = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int hideCustomBanner = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int loadBanner = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int loadCustomBanner = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int loadFullscreen = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int loadRewardedVideo = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int loadVideo = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int loadedLink = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int openLink = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int openLoadedLink = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int printEnvironmentInformation = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int releaseBanner = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int releaseCustomBanner = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int setUserAgeRangeMin = 2131034133;
			
			// aapt resource value: 0x7f05000b
			public const int showBanner = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int showCustomBannerPosition = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int showFullscreen = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int showLoadedFullscreen = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int showRewardedVideo = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int showVideo = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int startSession = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040015
			public const int app_name = 2130968597;
			
			// aapt resource value: 0x7f04000d
			public const int hideBanner = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int hideCustomBanner = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int loadFullscreen = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int loadRewardedVideo = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int loadVideo = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int loadedLink = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int openLink = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int openLoadedLink = 2130968594;
			
			// aapt resource value: 0x7f04000b
			public const int preLoadBanner = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int preLoadCustomBanner = 2130968586;
			
			// aapt resource value: 0x7f040013
			public const int printEnvironmentInformation = 2130968595;
			
			// aapt resource value: 0x7f040008
			public const int releaseBanner = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int releaseCustomBanner = 2130968585;
			
			// aapt resource value: 0x7f040014
			public const int setUserAgeRangeMin = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int showBanner = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int showCustomBannerPosition = 2130968590;
			
			// aapt resource value: 0x7f040001
			public const int showFullscreen = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int showLoadedFullscreen = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int showRewardedVideo = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int showVideo = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int startSession = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
